---
BONE_PHYSICALLY_SIMULATED = 1
---
BONE_PHYSICS_PROCEDURAL = 2
---
BONE_ALWAYS_PROCEDURAL = 4
---
BONE_SCREEN_ALIGN_SPHERE = 8
---
BONE_SCREEN_ALIGN_CYLINDER = 16
---
BONE_CALCULATE_MASK = 31
--- A hitbox is attached to this bone
BONE_USED_BY_HITBOX = 256
--- An attachment is attached to this bone
BONE_USED_BY_ATTACHMENT = 512
---
BONE_USED_BY_VERTEX_LOD0 = 1024
---
BONE_USED_BY_VERTEX_LOD1 = 2048
---
BONE_USED_BY_VERTEX_LOD2 = 4096
---
BONE_USED_BY_VERTEX_LOD3 = 8192
---
BONE_USED_BY_VERTEX_LOD4 = 16384
---
BONE_USED_BY_VERTEX_LOD5 = 32768
---
BONE_USED_BY_VERTEX_LOD6 = 65536
---
BONE_USED_BY_VERTEX_LOD7 = 131072
---
BONE_USED_BY_VERTEX_MASK = 261120
---
BONE_USED_BY_BONE_MERGE = 262144
--- Is this bone used by anything? ( If any BONE_USED_BY_* flags are true )
BONE_USED_BY_ANYTHING = 524032
---
BONE_USED_MASK = 524032

SENSORBONE = {}
---
SENSORBONE.SHOULDER_RIGHT = 8
---
SENSORBONE.SHOULDER_LEFT = 4
---
SENSORBONE.HIP = 0
---
SENSORBONE.ELBOW_RIGHT = 9
---
SENSORBONE.KNEE_RIGHT = 17
---
SENSORBONE.WRIST_RIGHT = 10
---
SENSORBONE.ANKLE_LEFT = 14
---
SENSORBONE.FOOT_LEFT = 15
---
SENSORBONE.WRIST_LEFT = 6
---
SENSORBONE.FOOT_RIGHT = 19
---
SENSORBONE.HAND_RIGHT = 11
---
SENSORBONE.SHOULDER = 2
---
SENSORBONE.HIP_LEFT = 12
---
SENSORBONE.HIP_RIGHT = 16
---
SENSORBONE.HAND_LEFT = 7
---
SENSORBONE.ANKLE_RIGHT = 18
---
SENSORBONE.SPINE = 1
---
SENSORBONE.ELBOW_LEFT = 5
---
SENSORBONE.KNEE_LEFT = 13
---
SENSORBONE.HEAD = 3

--- Slot for weapon gestures
GESTURE_SLOT_ATTACK_AND_RELOAD = 0
---
GESTURE_SLOT_GRENADE = 1
--- Slot for jump gestures
GESTURE_SLOT_JUMP = 2
--- Slot for swimming gestures
GESTURE_SLOT_SWIM = 3
--- Slot for flinching gestures
GESTURE_SLOT_FLINCH = 4
---
GESTURE_SLOT_VCD = 5
--- Slot for custom gestures
GESTURE_SLOT_CUSTOM = 6

---
PLAYER_IDLE = 0
---
PLAYER_WALK = 1
---
PLAYER_JUMP = 2
---
PLAYER_SUPERJUMP = 3
---
PLAYER_DIE = 4
--- Player attack according to current hold type, used in SWEPs
PLAYER_ATTACK1 = 5
---
PLAYER_IN_VEHICLE = 6
--- Player reload according to current hold type, used in SWEPs
PLAYER_RELOAD = 7
---
PLAYER_START_AIMING = 8
---
PLAYER_LEAVE_AIMING = 9

--- Primary attack
PLAYERANIMEVENT_ATTACK_PRIMARY = 0
--- Secondary attack
PLAYERANIMEVENT_ATTACK_SECONDARY = 1
--- Grenade throw
PLAYERANIMEVENT_ATTACK_GRENADE = 2
--- Reload
PLAYERANIMEVENT_RELOAD = 3
--- Looping reload (single-reload shotguns)
PLAYERANIMEVENT_RELOAD_LOOP = 4
--- Looping reload end
PLAYERANIMEVENT_RELOAD_END = 5
--- Jump
PLAYERANIMEVENT_JUMP = 6
--- Swim
PLAYERANIMEVENT_SWIM = 7
--- Die
PLAYERANIMEVENT_DIE = 8
---
PLAYERANIMEVENT_FLINCH_CHEST = 9
---
PLAYERANIMEVENT_FLINCH_HEAD = 10
---
PLAYERANIMEVENT_FLINCH_LEFTARM = 11
---
PLAYERANIMEVENT_FLINCH_RIGHTARM = 12
---
PLAYERANIMEVENT_FLINCH_LEFTLEG = 13
---
PLAYERANIMEVENT_FLINCH_RIGHTLEG = 14
---
PLAYERANIMEVENT_DOUBLEJUMP = 15
---
PLAYERANIMEVENT_CANCEL = 16
--- Spawn
PLAYERANIMEVENT_SPAWN = 17
---
PLAYERANIMEVENT_SNAP_YAW = 18
--- Custom activity
PLAYERANIMEVENT_CUSTOM = 19
--- Play activity in gesture slot
PLAYERANIMEVENT_CUSTOM_GESTURE = 20
--- Play sequence
PLAYERANIMEVENT_CUSTOM_SEQUENCE = 21
--- Play sequence in gesture slot
PLAYERANIMEVENT_CUSTOM_GESTURE_SEQUENCE = 22
--- Cancel reload animation
PLAYERANIMEVENT_CANCEL_RELOAD = 23
