--- @meta

--- Bone is physically simulated when physics are active  
_G.BONE_PHYSICALLY_SIMULATED = 1
--- Procedural when physics is active  
_G.BONE_PHYSICS_PROCEDURAL = 2
--- Bone is always procedurally animated  
_G.BONE_ALWAYS_PROCEDURAL = 4
--- Bone aligns to the screen, not constrained in motion.  
_G.BONE_SCREEN_ALIGN_SPHERE = 8
--- Bone aligns to the screen, constrained by it's own axis.  
_G.BONE_SCREEN_ALIGN_CYLINDER = 16
_G.BONE_CALCULATE_MASK = 31
--- A hitbox is attached to this bone  
_G.BONE_USED_BY_HITBOX = 256
--- An attachment is attached to this bone  
_G.BONE_USED_BY_ATTACHMENT = 512
_G.BONE_USED_BY_VERTEX_LOD0 = 1024
_G.BONE_USED_BY_VERTEX_LOD1 = 2048
_G.BONE_USED_BY_VERTEX_LOD2 = 4096
_G.BONE_USED_BY_VERTEX_LOD3 = 8192
_G.BONE_USED_BY_VERTEX_LOD4 = 16384
_G.BONE_USED_BY_VERTEX_LOD5 = 32768
_G.BONE_USED_BY_VERTEX_LOD6 = 65536
_G.BONE_USED_BY_VERTEX_LOD7 = 131072
_G.BONE_USED_BY_VERTEX_MASK = 261120
--- Bone is available for bone merge to occur against it  
_G.BONE_USED_BY_BONE_MERGE = 262144
--- Is this bone used by anything?  
--- ( If any BONE_USED_BY_* flags are true )  
_G.BONE_USED_BY_ANYTHING = 524032
_G.BONE_USED_MASK = 524032

--- Used by Entity:BoneHasFlag.  
--- @alias EBONE `BONE_PHYSICALLY_SIMULATED`|`BONE_PHYSICS_PROCEDURAL`|`BONE_ALWAYS_PROCEDURAL`|`BONE_SCREEN_ALIGN_SPHERE`|`BONE_SCREEN_ALIGN_CYLINDER`|`BONE_CALCULATE_MASK`|`BONE_USED_BY_HITBOX`|`BONE_USED_BY_ATTACHMENT`|`BONE_USED_BY_VERTEX_LOD0`|`BONE_USED_BY_VERTEX_LOD1`|`BONE_USED_BY_VERTEX_LOD2`|`BONE_USED_BY_VERTEX_LOD3`|`BONE_USED_BY_VERTEX_LOD4`|`BONE_USED_BY_VERTEX_LOD5`|`BONE_USED_BY_VERTEX_LOD6`|`BONE_USED_BY_VERTEX_LOD7`|`BONE_USED_BY_VERTEX_MASK`|`BONE_USED_BY_BONE_MERGE`|`BONE_USED_BY_ANYTHING`|`BONE_USED_MASK`
