--- @meta

_G.BUTTON_CODE_INVALID = -1
_G.BUTTON_CODE_NONE = 0
_G.BUTTON_CODE_LAST = 171
_G.BUTTON_CODE_COUNT = 172

--- Encompasses the range of Enums/KEY, Enums/MOUSE and Enums/JOYSTICK, all of which can be used by:  
--- * input.IsButtonDown  
--- * input.LookupKeyBinding  
--- * input.GetKeyName  
--- * input.GetKeyCode  
--- * GM:PlayerButtonDown  
--- * GM:PlayerButtonUp  
--- @alias EBUTTON_CODE `BUTTON_CODE_INVALID`|`BUTTON_CODE_NONE`|`BUTTON_CODE_LAST`|`BUTTON_CODE_COUNT`|`JOYSTICK_FIRST`|`JOYSTICK_FIRST_BUTTON`|`JOYSTICK_LAST_BUTTON`|`JOYSTICK_FIRST_POV_BUTTON`|`JOYSTICK_LAST_POV_BUTTON`|`JOYSTICK_FIRST_AXIS_BUTTON`|`JOYSTICK_LAST_AXIS_BUTTON`|`JOYSTICK_LAST`|`KEY_FIRST`|`KEY_NONE`|`KEY_0`|`KEY_1`|`KEY_2`|`KEY_3`|`KEY_4`|`KEY_5`|`KEY_6`|`KEY_7`|`KEY_8`|`KEY_9`|`KEY_A`|`KEY_B`|`KEY_C`|`KEY_D`|`KEY_E`|`KEY_F`|`KEY_G`|`KEY_H`|`KEY_I`|`KEY_J`|`KEY_K`|`KEY_L`|`KEY_M`|`KEY_N`|`KEY_O`|`KEY_P`|`KEY_Q`|`KEY_R`|`KEY_S`|`KEY_T`|`KEY_U`|`KEY_V`|`KEY_W`|`KEY_X`|`KEY_Y`|`KEY_Z`|`KEY_PAD_0`|`KEY_PAD_1`|`KEY_PAD_2`|`KEY_PAD_3`|`KEY_PAD_4`|`KEY_PAD_5`|`KEY_PAD_6`|`KEY_PAD_7`|`KEY_PAD_8`|`KEY_PAD_9`|`KEY_PAD_DIVIDE`|`KEY_PAD_MULTIPLY`|`KEY_PAD_MINUS`|`KEY_PAD_PLUS`|`KEY_PAD_ENTER`|`KEY_PAD_DECIMAL`|`KEY_LBRACKET`|`KEY_RBRACKET`|`KEY_SEMICOLON`|`KEY_APOSTROPHE`|`KEY_BACKQUOTE`|`KEY_COMMA`|`KEY_PERIOD`|`KEY_SLASH`|`KEY_BACKSLASH`|`KEY_MINUS`|`KEY_EQUAL`|`KEY_ENTER`|`KEY_SPACE`|`KEY_BACKSPACE`|`KEY_TAB`|`KEY_CAPSLOCK`|`KEY_NUMLOCK`|`KEY_ESCAPE`|`KEY_SCROLLLOCK`|`KEY_INSERT`|`KEY_DELETE`|`KEY_HOME`|`KEY_END`|`KEY_PAGEUP`|`KEY_PAGEDOWN`|`KEY_BREAK`|`KEY_LSHIFT`|`KEY_RSHIFT`|`KEY_LALT`|`KEY_RALT`|`KEY_LCONTROL`|`KEY_RCONTROL`|`KEY_LWIN`|`KEY_RWIN`|`KEY_APP`|`KEY_UP`|`KEY_LEFT`|`KEY_DOWN`|`KEY_RIGHT`|`KEY_F1`|`KEY_F2`|`KEY_F3`|`KEY_F4`|`KEY_F5`|`KEY_F6`|`KEY_F7`|`KEY_F8`|`KEY_F9`|`KEY_F10`|`KEY_F11`|`KEY_F12`|`KEY_CAPSLOCKTOGGLE`|`KEY_NUMLOCKTOGGLE`|`KEY_LAST`|`KEY_SCROLLLOCKTOGGLE`|`KEY_COUNT`|`KEY_XBUTTON_A`|`KEY_XBUTTON_B`|`KEY_XBUTTON_X`|`KEY_XBUTTON_Y`|`KEY_XBUTTON_LEFT_SHOULDER`|`KEY_XBUTTON_RIGHT_SHOULDER`|`KEY_XBUTTON_BACK`|`KEY_XBUTTON_START`|`KEY_XBUTTON_STICK1`|`KEY_XBUTTON_STICK2`|`KEY_XBUTTON_UP`|`KEY_XBUTTON_RIGHT`|`KEY_XBUTTON_DOWN`|`KEY_XBUTTON_LEFT`|`KEY_XSTICK1_RIGHT`|`KEY_XSTICK1_LEFT`|`KEY_XSTICK1_DOWN`|`KEY_XSTICK1_UP`|`KEY_XBUTTON_LTRIGGER`|`KEY_XBUTTON_RTRIGGER`|`KEY_XSTICK2_RIGHT`|`KEY_XSTICK2_LEFT`|`KEY_XSTICK2_DOWN`|`KEY_XSTICK2_UP`|`MOUSE_FIRST`|`MOUSE_LEFT`|`MOUSE_RIGHT`|`MOUSE_MIDDLE`|`MOUSE_4`|`MOUSE_5`|`MOUSE_WHEEL_UP`|`MOUSE_WHEEL_DOWN`|`MOUSE_LAST`|`MOUSE_COUNT`
