--- @meta

_G.COND.BEHIND_ENEMY = 29
_G.COND.BETTER_WEAPON_AVAILABLE = 46
_G.COND.CAN_MELEE_ATTACK1 = 23
_G.COND.CAN_MELEE_ATTACK2 = 24
_G.COND.CAN_RANGE_ATTACK1 = 21
_G.COND.CAN_RANGE_ATTACK2 = 22
_G.COND.ENEMY_DEAD = 30
_G.COND.ENEMY_FACING_ME = 28
_G.COND.ENEMY_OCCLUDED = 13
_G.COND.ENEMY_TOO_FAR = 27
_G.COND.ENEMY_UNREACHABLE = 31
_G.COND.ENEMY_WENT_NULL = 12
_G.COND.FLOATING_OFF_GROUND = 61
_G.COND.GIVE_WAY = 48
_G.COND.HAVE_ENEMY_LOS = 15
_G.COND.HAVE_TARGET_LOS = 16
_G.COND.HEALTH_ITEM_AVAILABLE = 47
_G.COND.HEAR_BUGBAIT = 52
_G.COND.HEAR_BULLET_IMPACT = 56
_G.COND.HEAR_COMBAT = 53
_G.COND.HEAR_DANGER = 50
_G.COND.HEAR_MOVE_AWAY = 58
_G.COND.HEAR_PHYSICS_DANGER = 57
_G.COND.HEAR_PLAYER = 55
_G.COND.HEAR_SPOOKY = 59
_G.COND.HEAR_THUMPER = 51
_G.COND.HEAR_WORLD = 54
_G.COND.HEAVY_DAMAGE = 18
_G.COND.IDLE_INTERRUPT = 2
_G.COND.IN_PVS = 1
_G.COND.LIGHT_DAMAGE = 17
_G.COND.LOST_ENEMY = 11
_G.COND.LOST_PLAYER = 33
_G.COND.LOW_PRIMARY_AMMO = 3
_G.COND.MOBBED_BY_ENEMIES = 62
_G.COND.NEW_ENEMY = 26
_G.COND.NO_CUSTOM_INTERRUPTS = 70
_G.COND.NO_HEAR_DANGER = 60
_G.COND.NO_PRIMARY_AMMO = 4
_G.COND.NO_SECONDARY_AMMO = 5
_G.COND.NO_WEAPON = 6
--- No additional conditions are being played  
_G.COND.NONE = 0
_G.COND.NOT_FACING_ATTACK = 40
--- Freezes NPC movement  
_G.COND.NPC_FREEZE = 67
--- Unfreezes NPC movement  
_G.COND.NPC_UNFREEZE = 68
_G.COND.PHYSICS_DAMAGE = 19
_G.COND.PLAYER_ADDED_TO_SQUAD = 64
_G.COND.PLAYER_PUSHING = 66
_G.COND.PLAYER_REMOVED_FROM_SQUAD = 65
_G.COND.PROVOKED = 25
_G.COND.RECEIVED_ORDERS = 63
_G.COND.REPEATED_DAMAGE = 20
_G.COND.SCHEDULE_DONE = 36
_G.COND.SEE_DISLIKE = 9
_G.COND.SEE_ENEMY = 10
_G.COND.SEE_FEAR = 8
_G.COND.SEE_HATE = 7
_G.COND.SEE_NEMESIS = 34
_G.COND.SEE_PLAYER = 32
_G.COND.SMELL = 37
_G.COND.TALKER_RESPOND_TO_QUESTION = 69
_G.COND.TARGET_OCCLUDED = 14
_G.COND.TASK_FAILED = 35
_G.COND.TOO_CLOSE_TO_ATTACK = 38
_G.COND.TOO_FAR_TO_ATTACK = 39
_G.COND.WAY_CLEAR = 49
_G.COND.WEAPON_BLOCKED_BY_FRIEND = 42
_G.COND.WEAPON_HAS_LOS = 41
_G.COND.WEAPON_PLAYER_IN_SPREAD = 43
_G.COND.WEAPON_PLAYER_NEAR_TARGET = 44
_G.COND.WEAPON_SIGHT_OCCLUDED = 45

--- Enumerations for NPC conditions, used by NPC:SetCondition. Serverside only.  
--- ℹ **NOTE**: Unlike other Enums `COND` is a table that contains all the enums.  
--- There are more conditions than listed here after **COND_NO_CUSTOM_INTERRUPTS**(70)  
--- but the name depends on what's returned by NPC:ConditionName  
--- @alias ECOND `COND.BEHIND_ENEMY`|`COND.BETTER_WEAPON_AVAILABLE`|`COND.CAN_MELEE_ATTACK1`|`COND.CAN_MELEE_ATTACK2`|`COND.CAN_RANGE_ATTACK1`|`COND.CAN_RANGE_ATTACK2`|`COND.ENEMY_DEAD`|`COND.ENEMY_FACING_ME`|`COND.ENEMY_OCCLUDED`|`COND.ENEMY_TOO_FAR`|`COND.ENEMY_UNREACHABLE`|`COND.ENEMY_WENT_NULL`|`COND.FLOATING_OFF_GROUND`|`COND.GIVE_WAY`|`COND.HAVE_ENEMY_LOS`|`COND.HAVE_TARGET_LOS`|`COND.HEALTH_ITEM_AVAILABLE`|`COND.HEAR_BUGBAIT`|`COND.HEAR_BULLET_IMPACT`|`COND.HEAR_COMBAT`|`COND.HEAR_DANGER`|`COND.HEAR_MOVE_AWAY`|`COND.HEAR_PHYSICS_DANGER`|`COND.HEAR_PLAYER`|`COND.HEAR_SPOOKY`|`COND.HEAR_THUMPER`|`COND.HEAR_WORLD`|`COND.HEAVY_DAMAGE`|`COND.IDLE_INTERRUPT`|`COND.IN_PVS`|`COND.LIGHT_DAMAGE`|`COND.LOST_ENEMY`|`COND.LOST_PLAYER`|`COND.LOW_PRIMARY_AMMO`|`COND.MOBBED_BY_ENEMIES`|`COND.NEW_ENEMY`|`COND.NO_CUSTOM_INTERRUPTS`|`COND.NO_HEAR_DANGER`|`COND.NO_PRIMARY_AMMO`|`COND.NO_SECONDARY_AMMO`|`COND.NO_WEAPON`|`COND.NONE`|`COND.NOT_FACING_ATTACK`|`COND.NPC_FREEZE`|`COND.NPC_UNFREEZE`|`COND.PHYSICS_DAMAGE`|`COND.PLAYER_ADDED_TO_SQUAD`|`COND.PLAYER_PUSHING`|`COND.PLAYER_REMOVED_FROM_SQUAD`|`COND.PROVOKED`|`COND.RECEIVED_ORDERS`|`COND.REPEATED_DAMAGE`|`COND.SCHEDULE_DONE`|`COND.SEE_DISLIKE`|`COND.SEE_ENEMY`|`COND.SEE_FEAR`|`COND.SEE_HATE`|`COND.SEE_NEMESIS`|`COND.SEE_PLAYER`|`COND.SMELL`|`COND.TALKER_RESPOND_TO_QUESTION`|`COND.TARGET_OCCLUDED`|`COND.TASK_FAILED`|`COND.TOO_CLOSE_TO_ATTACK`|`COND.TOO_FAR_TO_ATTACK`|`COND.WAY_CLEAR`|`COND.WEAPON_BLOCKED_BY_FRIEND`|`COND.WEAPON_HAS_LOS`|`COND.WEAPON_PLAYER_IN_SPREAD`|`COND.WEAPON_PLAYER_NEAR_TARGET`|`COND.WEAPON_SIGHT_OCCLUDED`
