--- @meta

--- Things that are not solid  
_G.CONTENTS_EMPTY = 0
--- Things that are solid  
_G.CONTENTS_SOLID = 1
--- Glass  
_G.CONTENTS_WINDOW = 2
_G.CONTENTS_AUX = 4
--- Bullets go through, solids don't  
_G.CONTENTS_GRATE = 8
_G.CONTENTS_SLIME = 16
--- Hits world but not skybox  
_G.CONTENTS_WATER = 32
--- Things that block line of sight  
_G.CONTENTS_BLOCKLOS = 64
--- Things that block light  
_G.CONTENTS_OPAQUE = 128
_G.CONTENTS_TESTFOGVOLUME = 256
_G.CONTENTS_TEAM4 = 512
_G.CONTENTS_TEAM3 = 1024
_G.CONTENTS_TEAM1 = 2048
_G.CONTENTS_TEAM2 = 4096
_G.CONTENTS_IGNORE_NODRAW_OPAQUE = 8192
_G.CONTENTS_MOVEABLE = 16384
_G.CONTENTS_AREAPORTAL = 32768
_G.CONTENTS_PLAYERCLIP = 65536
_G.CONTENTS_MONSTERCLIP = 131072
_G.CONTENTS_CURRENT_0 = 262144
_G.CONTENTS_CURRENT_180 = 1048576
_G.CONTENTS_CURRENT_270 = 2097152
_G.CONTENTS_CURRENT_90 = 524288
_G.CONTENTS_CURRENT_DOWN = 8388608
_G.CONTENTS_CURRENT_UP = 4194304
--- Includes, among other things, client-side ragdolls and prop gibs  
_G.CONTENTS_DEBRIS = 67108864
_G.CONTENTS_DETAIL = 134217728
--- Hitbox  
_G.CONTENTS_HITBOX = 1073741824
--- Ladder  
_G.CONTENTS_LADDER = 536870912
--- NPCs  
_G.CONTENTS_MONSTER = 33554432
_G.CONTENTS_ORIGIN = 16777216
--- Hits world but not skybox  
_G.CONTENTS_TRANSLUCENT = 268435456
--- Last visible contents enumeration  
_G.LAST_VISIBLE_CONTENTS = 128
--- Sum of all the visible contents enumerations  
_G.ALL_VISIBLE_CONTENTS = 255

--- Enumerations used by util.PointContents and PhysObj:SetContents as tracer masks, and by ENT.PhysicsSolidMask for collision masking.  
--- @alias ECONTENTS `CONTENTS_EMPTY`|`CONTENTS_SOLID`|`CONTENTS_WINDOW`|`CONTENTS_AUX`|`CONTENTS_GRATE`|`CONTENTS_SLIME`|`CONTENTS_WATER`|`CONTENTS_BLOCKLOS`|`CONTENTS_OPAQUE`|`CONTENTS_TESTFOGVOLUME`|`CONTENTS_TEAM4`|`CONTENTS_TEAM3`|`CONTENTS_TEAM1`|`CONTENTS_TEAM2`|`CONTENTS_IGNORE_NODRAW_OPAQUE`|`CONTENTS_MOVEABLE`|`CONTENTS_AREAPORTAL`|`CONTENTS_PLAYERCLIP`|`CONTENTS_MONSTERCLIP`|`CONTENTS_CURRENT_0`|`CONTENTS_CURRENT_180`|`CONTENTS_CURRENT_270`|`CONTENTS_CURRENT_90`|`CONTENTS_CURRENT_DOWN`|`CONTENTS_CURRENT_UP`|`CONTENTS_DEBRIS`|`CONTENTS_DETAIL`|`CONTENTS_HITBOX`|`CONTENTS_LADDER`|`CONTENTS_MONSTER`|`CONTENTS_ORIGIN`|`CONTENTS_TRANSLUCENT`|`LAST_VISIBLE_CONTENTS`|`ALL_VISIBLE_CONTENTS`
