--- @meta

_G.KEY_FIRST = 0
_G.KEY_NONE = 0
--- Normal number 0 key  
_G.KEY_0 = 1
--- Normal number 1 key  
_G.KEY_1 = 2
--- Normal number 2 key  
_G.KEY_2 = 3
--- Normal number 3 key  
_G.KEY_3 = 4
--- Normal number 4 key  
_G.KEY_4 = 5
--- Normal number 5 key  
_G.KEY_5 = 6
--- Normal number 6 key  
_G.KEY_6 = 7
--- Normal number 7 key  
_G.KEY_7 = 8
--- Normal number 8 key  
_G.KEY_8 = 9
--- Normal number 9 key  
_G.KEY_9 = 10
_G.KEY_A = 11
_G.KEY_B = 12
_G.KEY_C = 13
_G.KEY_D = 14
_G.KEY_E = 15
_G.KEY_F = 16
_G.KEY_G = 17
_G.KEY_H = 18
_G.KEY_I = 19
_G.KEY_J = 20
_G.KEY_K = 21
_G.KEY_L = 22
_G.KEY_M = 23
_G.KEY_N = 24
_G.KEY_O = 25
_G.KEY_P = 26
_G.KEY_Q = 27
_G.KEY_R = 28
_G.KEY_S = 29
_G.KEY_T = 30
_G.KEY_U = 31
_G.KEY_V = 32
_G.KEY_W = 33
_G.KEY_X = 34
_G.KEY_Y = 35
_G.KEY_Z = 36
--- Keypad number 0 key  
_G.KEY_PAD_0 = 37
--- Keypad number 1 key  
_G.KEY_PAD_1 = 38
--- Keypad number 2 key  
_G.KEY_PAD_2 = 39
--- Keypad number 3 key  
_G.KEY_PAD_3 = 40
--- Keypad number 4 key  
_G.KEY_PAD_4 = 41
--- Keypad number 5 key  
_G.KEY_PAD_5 = 42
--- Keypad number 6 key  
_G.KEY_PAD_6 = 43
--- Keypad number 7 key  
_G.KEY_PAD_7 = 44
--- Keypad number 8 key  
_G.KEY_PAD_8 = 45
--- Keypad number 9 key  
_G.KEY_PAD_9 = 46
--- Keypad division/slash key (/)  
_G.KEY_PAD_DIVIDE = 47
--- Keypad asterisk key (*)  
_G.KEY_PAD_MULTIPLY = 48
--- Keypad minus key  
_G.KEY_PAD_MINUS = 49
--- Keypad plus key  
_G.KEY_PAD_PLUS = 50
--- Keypad enter key  
_G.KEY_PAD_ENTER = 51
--- Keypad dot key (.)  
_G.KEY_PAD_DECIMAL = 52
_G.KEY_LBRACKET = 53
_G.KEY_RBRACKET = 54
_G.KEY_SEMICOLON = 55
_G.KEY_APOSTROPHE = 56
_G.KEY_BACKQUOTE = 57
_G.KEY_COMMA = 58
_G.KEY_PERIOD = 59
_G.KEY_SLASH = 60
_G.KEY_BACKSLASH = 61
_G.KEY_MINUS = 62
_G.KEY_EQUAL = 63
_G.KEY_ENTER = 64
_G.KEY_SPACE = 65
_G.KEY_BACKSPACE = 66
_G.KEY_TAB = 67
_G.KEY_CAPSLOCK = 68
_G.KEY_NUMLOCK = 69
_G.KEY_ESCAPE = 70
_G.KEY_SCROLLLOCK = 71
_G.KEY_INSERT = 72
_G.KEY_DELETE = 73
_G.KEY_HOME = 74
_G.KEY_END = 75
_G.KEY_PAGEUP = 76
_G.KEY_PAGEDOWN = 77
_G.KEY_BREAK = 78
--- The left Shift key, has been seen to be triggered by Right Shift in PANEL:OnKeyCodePressed  
_G.KEY_LSHIFT = 79
_G.KEY_RSHIFT = 80
_G.KEY_LALT = 81
_G.KEY_RALT = 82
_G.KEY_LCONTROL = 83
_G.KEY_RCONTROL = 84
--- The left Windows key or the Command key on Mac OSX  
_G.KEY_LWIN = 85
--- The right Windows key or the Command key on Mac OSX  
_G.KEY_RWIN = 86
_G.KEY_APP = 87
_G.KEY_UP = 88
_G.KEY_LEFT = 89
_G.KEY_DOWN = 90
_G.KEY_RIGHT = 91
_G.KEY_F1 = 92
_G.KEY_F2 = 93
_G.KEY_F3 = 94
_G.KEY_F4 = 95
_G.KEY_F5 = 96
_G.KEY_F6 = 97
_G.KEY_F7 = 98
--- ⚠ **WARNING**: By default, it serves as bind "load quick", which loads the save by forcing the player to exit the server.  
_G.KEY_F8 = 99
_G.KEY_F9 = 100
_G.KEY_F10 = 101
_G.KEY_F11 = 102
_G.KEY_F12 = 103
_G.KEY_CAPSLOCKTOGGLE = 104
_G.KEY_NUMLOCKTOGGLE = 105
_G.KEY_LAST = 106
_G.KEY_SCROLLLOCKTOGGLE = 106
_G.KEY_COUNT = 107
_G.KEY_XBUTTON_A = 114
_G.KEY_XBUTTON_B = 115
_G.KEY_XBUTTON_X = 116
_G.KEY_XBUTTON_Y = 117
_G.KEY_XBUTTON_LEFT_SHOULDER = 118
_G.KEY_XBUTTON_RIGHT_SHOULDER = 119
_G.KEY_XBUTTON_BACK = 120
_G.KEY_XBUTTON_START = 121
_G.KEY_XBUTTON_STICK1 = 122
_G.KEY_XBUTTON_STICK2 = 123
_G.KEY_XBUTTON_UP = 146
_G.KEY_XBUTTON_RIGHT = 147
_G.KEY_XBUTTON_DOWN = 148
_G.KEY_XBUTTON_LEFT = 149
_G.KEY_XSTICK1_RIGHT = 150
_G.KEY_XSTICK1_LEFT = 151
_G.KEY_XSTICK1_DOWN = 152
_G.KEY_XSTICK1_UP = 153
_G.KEY_XBUTTON_LTRIGGER = 154
_G.KEY_XBUTTON_RTRIGGER = 155
_G.KEY_XSTICK2_RIGHT = 156
_G.KEY_XSTICK2_LEFT = 157
_G.KEY_XSTICK2_DOWN = 158
_G.KEY_XSTICK2_UP = 159

--- Enumerations used by:  
--- * input.IsKeyDown  
--- * input.WasKeyPressed  
--- * input.WasKeyReleased  
--- * input.WasKeyTyped  
--- * input.IsKeyTrapping  
--- * input.GetKeyName  
--- * input.LookupBinding  
--- * PANEL:OnKeyCodePressed  
--- * PANEL:OnKeyCodeReleased  
--- It's also part of the Enums/BUTTON_CODE.  
--- @alias EKEY `KEY_FIRST`|`KEY_NONE`|`KEY_0`|`KEY_1`|`KEY_2`|`KEY_3`|`KEY_4`|`KEY_5`|`KEY_6`|`KEY_7`|`KEY_8`|`KEY_9`|`KEY_A`|`KEY_B`|`KEY_C`|`KEY_D`|`KEY_E`|`KEY_F`|`KEY_G`|`KEY_H`|`KEY_I`|`KEY_J`|`KEY_K`|`KEY_L`|`KEY_M`|`KEY_N`|`KEY_O`|`KEY_P`|`KEY_Q`|`KEY_R`|`KEY_S`|`KEY_T`|`KEY_U`|`KEY_V`|`KEY_W`|`KEY_X`|`KEY_Y`|`KEY_Z`|`KEY_PAD_0`|`KEY_PAD_1`|`KEY_PAD_2`|`KEY_PAD_3`|`KEY_PAD_4`|`KEY_PAD_5`|`KEY_PAD_6`|`KEY_PAD_7`|`KEY_PAD_8`|`KEY_PAD_9`|`KEY_PAD_DIVIDE`|`KEY_PAD_MULTIPLY`|`KEY_PAD_MINUS`|`KEY_PAD_PLUS`|`KEY_PAD_ENTER`|`KEY_PAD_DECIMAL`|`KEY_LBRACKET`|`KEY_RBRACKET`|`KEY_SEMICOLON`|`KEY_APOSTROPHE`|`KEY_BACKQUOTE`|`KEY_COMMA`|`KEY_PERIOD`|`KEY_SLASH`|`KEY_BACKSLASH`|`KEY_MINUS`|`KEY_EQUAL`|`KEY_ENTER`|`KEY_SPACE`|`KEY_BACKSPACE`|`KEY_TAB`|`KEY_CAPSLOCK`|`KEY_NUMLOCK`|`KEY_ESCAPE`|`KEY_SCROLLLOCK`|`KEY_INSERT`|`KEY_DELETE`|`KEY_HOME`|`KEY_END`|`KEY_PAGEUP`|`KEY_PAGEDOWN`|`KEY_BREAK`|`KEY_LSHIFT`|`KEY_RSHIFT`|`KEY_LALT`|`KEY_RALT`|`KEY_LCONTROL`|`KEY_RCONTROL`|`KEY_LWIN`|`KEY_RWIN`|`KEY_APP`|`KEY_UP`|`KEY_LEFT`|`KEY_DOWN`|`KEY_RIGHT`|`KEY_F1`|`KEY_F2`|`KEY_F3`|`KEY_F4`|`KEY_F5`|`KEY_F6`|`KEY_F7`|`KEY_F8`|`KEY_F9`|`KEY_F10`|`KEY_F11`|`KEY_F12`|`KEY_CAPSLOCKTOGGLE`|`KEY_NUMLOCKTOGGLE`|`KEY_LAST`|`KEY_SCROLLLOCKTOGGLE`|`KEY_COUNT`|`KEY_XBUTTON_A`|`KEY_XBUTTON_B`|`KEY_XBUTTON_X`|`KEY_XBUTTON_Y`|`KEY_XBUTTON_LEFT_SHOULDER`|`KEY_XBUTTON_RIGHT_SHOULDER`|`KEY_XBUTTON_BACK`|`KEY_XBUTTON_START`|`KEY_XBUTTON_STICK1`|`KEY_XBUTTON_STICK2`|`KEY_XBUTTON_UP`|`KEY_XBUTTON_RIGHT`|`KEY_XBUTTON_DOWN`|`KEY_XBUTTON_LEFT`|`KEY_XSTICK1_RIGHT`|`KEY_XSTICK1_LEFT`|`KEY_XSTICK1_DOWN`|`KEY_XSTICK1_UP`|`KEY_XBUTTON_LTRIGGER`|`KEY_XBUTTON_RTRIGGER`|`KEY_XSTICK2_RIGHT`|`KEY_XSTICK2_LEFT`|`KEY_XSTICK2_DOWN`|`KEY_XSTICK2_UP`
