--- @meta

--- Primary attack  
_G.PLAYERANIMEVENT_ATTACK_PRIMARY = 0
--- Secondary attack  
_G.PLAYERANIMEVENT_ATTACK_SECONDARY = 1
--- Grenade throw  
_G.PLAYERANIMEVENT_ATTACK_GRENADE = 2
--- Reload  
_G.PLAYERANIMEVENT_RELOAD = 3
--- Looping reload (single-reload shotguns)  
_G.PLAYERANIMEVENT_RELOAD_LOOP = 4
--- Looping reload end  
_G.PLAYERANIMEVENT_RELOAD_END = 5
--- Jump  
_G.PLAYERANIMEVENT_JUMP = 6
--- Swim  
_G.PLAYERANIMEVENT_SWIM = 7
--- Die  
_G.PLAYERANIMEVENT_DIE = 8
_G.PLAYERANIMEVENT_FLINCH_CHEST = 9
_G.PLAYERANIMEVENT_FLINCH_HEAD = 10
_G.PLAYERANIMEVENT_FLINCH_LEFTARM = 11
_G.PLAYERANIMEVENT_FLINCH_RIGHTARM = 12
_G.PLAYERANIMEVENT_FLINCH_LEFTLEG = 13
_G.PLAYERANIMEVENT_FLINCH_RIGHTLEG = 14
_G.PLAYERANIMEVENT_DOUBLEJUMP = 15
_G.PLAYERANIMEVENT_CANCEL = 16
--- Spawn  
_G.PLAYERANIMEVENT_SPAWN = 17
_G.PLAYERANIMEVENT_SNAP_YAW = 18
--- Custom activity  
_G.PLAYERANIMEVENT_CUSTOM = 19
--- Play activity in gesture slot  
_G.PLAYERANIMEVENT_CUSTOM_GESTURE = 20
--- Play sequence  
_G.PLAYERANIMEVENT_CUSTOM_SEQUENCE = 21
--- Play sequence in gesture slot  
_G.PLAYERANIMEVENT_CUSTOM_GESTURE_SEQUENCE = 22
--- Cancel reload animation  
_G.PLAYERANIMEVENT_CANCEL_RELOAD = 23

--- Used by GM:DoAnimationEvent and Player:DoCustomAnimEvent.  
--- @alias EPLAYERANIMEVENT `PLAYERANIMEVENT_ATTACK_PRIMARY`|`PLAYERANIMEVENT_ATTACK_SECONDARY`|`PLAYERANIMEVENT_ATTACK_GRENADE`|`PLAYERANIMEVENT_RELOAD`|`PLAYERANIMEVENT_RELOAD_LOOP`|`PLAYERANIMEVENT_RELOAD_END`|`PLAYERANIMEVENT_JUMP`|`PLAYERANIMEVENT_SWIM`|`PLAYERANIMEVENT_DIE`|`PLAYERANIMEVENT_FLINCH_CHEST`|`PLAYERANIMEVENT_FLINCH_HEAD`|`PLAYERANIMEVENT_FLINCH_LEFTARM`|`PLAYERANIMEVENT_FLINCH_RIGHTARM`|`PLAYERANIMEVENT_FLINCH_LEFTLEG`|`PLAYERANIMEVENT_FLINCH_RIGHTLEG`|`PLAYERANIMEVENT_DOUBLEJUMP`|`PLAYERANIMEVENT_CANCEL`|`PLAYERANIMEVENT_SPAWN`|`PLAYERANIMEVENT_SNAP_YAW`|`PLAYERANIMEVENT_CUSTOM`|`PLAYERANIMEVENT_CUSTOM_GESTURE`|`PLAYERANIMEVENT_CUSTOM_SEQUENCE`|`PLAYERANIMEVENT_CUSTOM_GESTURE_SEQUENCE`|`PLAYERANIMEVENT_CANCEL_RELOAD`
