--- @meta

_G.SENSORBONE.SHOULDER_RIGHT = 8
_G.SENSORBONE.SHOULDER_LEFT = 4
_G.SENSORBONE.HIP = 0
_G.SENSORBONE.ELBOW_RIGHT = 9
_G.SENSORBONE.KNEE_RIGHT = 17
_G.SENSORBONE.WRIST_RIGHT = 10
_G.SENSORBONE.ANKLE_LEFT = 14
_G.SENSORBONE.FOOT_LEFT = 15
_G.SENSORBONE.WRIST_LEFT = 6
_G.SENSORBONE.FOOT_RIGHT = 19
_G.SENSORBONE.HAND_RIGHT = 11
_G.SENSORBONE.SHOULDER = 2
_G.SENSORBONE.HIP_LEFT = 12
_G.SENSORBONE.HIP_RIGHT = 16
_G.SENSORBONE.HAND_LEFT = 7
_G.SENSORBONE.ANKLE_RIGHT = 18
_G.SENSORBONE.SPINE = 1
_G.SENSORBONE.ELBOW_LEFT = 5
_G.SENSORBONE.KNEE_LEFT = 13
_G.SENSORBONE.HEAD = 3

--- Enumerations used by Kinect SDK bindings.  
--- @alias ESENSORBONE `SENSORBONE.SHOULDER_RIGHT`|`SENSORBONE.SHOULDER_LEFT`|`SENSORBONE.HIP`|`SENSORBONE.ELBOW_RIGHT`|`SENSORBONE.KNEE_RIGHT`|`SENSORBONE.WRIST_RIGHT`|`SENSORBONE.ANKLE_LEFT`|`SENSORBONE.FOOT_LEFT`|`SENSORBONE.WRIST_LEFT`|`SENSORBONE.FOOT_RIGHT`|`SENSORBONE.HAND_RIGHT`|`SENSORBONE.SHOULDER`|`SENSORBONE.HIP_LEFT`|`SENSORBONE.HIP_RIGHT`|`SENSORBONE.HAND_LEFT`|`SENSORBONE.ANKLE_RIGHT`|`SENSORBONE.SPINE`|`SENSORBONE.ELBOW_LEFT`|`SENSORBONE.KNEE_LEFT`|`SENSORBONE.HEAD`
