--- @meta

_G.SIGNONSTATE_NONE = 0
_G.SIGNONSTATE_CHALLENGE = 1
_G.SIGNONSTATE_CONNECTED = 2
_G.SIGNONSTATE_NEW = 3
_G.SIGNONSTATE_PRESPAWN = 4
_G.SIGNONSTATE_SPAWN = 5
_G.SIGNONSTATE_FULL = 6
_G.SIGNONSTATE_CHANGELEVEL = 7

--- Used by GM:ClientSignOnStateChanged.  
--- @alias ESIGNONSTATE `SIGNONSTATE_NONE`|`SIGNONSTATE_CHALLENGE`|`SIGNONSTATE_CONNECTED`|`SIGNONSTATE_NEW`|`SIGNONSTATE_PRESPAWN`|`SIGNONSTATE_SPAWN`|`SIGNONSTATE_FULL`|`SIGNONSTATE_CHANGELEVEL`
