-- TODO: These need arguments and EmmyLua annotations

function AccessorFunc(p1,p2,p3,p4) end
function AddCSLuaFile(...) end
function AddConsoleCommand(...) end
function AddOriginToPVS(...) end
function Add_NPC_Class(p1) end
function AddonMaterial(...) end
function Angle(...) end
function AngleRand(p1,p2) end
function BroadcastLua(...) end
function BuildNetworkedVarsTable(...) end
function ChangeTooltip(p1) end
function ClientsideModel(...) end
function ClientsideRagdoll(...) end
function ClientsideScene(...) end
function CloseDermaMenus() end
function Color(p1,p2,p3,p4) end
function ColorAlpha(p1,p2) end
function ColorRand(p1) end
function ColorToHSL(...) end
function ColorToHSV(...) end
function CompileFile(...) end
function CompileString(...) end
function ConVarExists(...) end
function CreateAllFunction(p1) end
function CreateClientConVar(p1,p2,p3,p4,p5,p6,p7) end
function CreateConVar(...) end
function CreateMaterial(...) end
function CreateParticleSystem(...) end
function CreatePhysCollideBox(...) end
function CreatePhysCollidesFromModel(...) end
function CreateSound(...) end
function CreateSprite(p1) end
function CurTime(...) end
function DOFModeHack(...) end
function DOF_Kill() end
function DOF_Start() end
function DTVar_ReceiveProxyGL(p1,p2,p3,p4) end
function DamageInfo(...) end
function DebugInfo(...) end
function DeriveGamemode(...) end
function DermaMenu(p1,p2) end
function Derma_Anim(p1,p2,p3) end
function Derma_DrawBackgroundBlur(p1,p2) end
function Derma_Hook(p1,p2,p3,p4) end
function Derma_Install_Convar_Functions(p1) end
function Derma_Message(p1,p2,p3) end
function Derma_Query(...) end
function Derma_StringRequest(p1,p2,p3,p4,p5,p6,p7) end
function DisableClipping(...) end
function DrawBloom(p1,p2,p3,p4,p5,p6,p7,p8,p9) end
function DrawColorModify(p1) end
function DrawMaterialOverlay(p1,p2) end
function DrawMotionBlur(p1,p2,p3) end
function DrawSharpen(p1,p2) end
function DrawSobel(p1) end
function DrawSunbeams(p1,p2,p3,p4,p5) end
function DrawTexturize(p1,p2) end
function DrawToyTown(p1,p2) end
function DropEntityIfHeld(...) end
function DynamicLight(...) end
function EffectData(...) end
function Either(p1,p2,p3) end
function EmitSentence(...) end
function EmitSound(...) end
function EndTooltip(p1) end
function Entity(...) end
function Error(...) end
function ErrorNoHalt(...) end
function EyeAngles(...) end
function EyePos(...) end
function EyeVector(...) end
function FindMetaTable(...) end
function FindTooltip(p1) end
function Format(...) end
function FrameNumber(...) end
function FrameTime(...) end
function GetConVar(p1) end
function GetConVarNumber(p1) end
function GetConVarString(p1) end
function GetConVar_Internal(...) end
function GetGlobal2Angle(...) end
function GetGlobal2Bool(...) end
function GetGlobal2Entity(...) end
function GetGlobal2Float(...) end
function GetGlobal2Int(...) end
function GetGlobal2String(...) end
function GetGlobal2Var(...) end
function GetGlobal2Vector(...) end
function GetGlobalAngle(...) end
function GetGlobalBool(...) end
function GetGlobalEntity(...) end
function GetGlobalFloat(...) end
function GetGlobalInt(...) end
function GetGlobalString(...) end
function GetGlobalVar(...) end
function GetGlobalVector(...) end
function GetHUDPanel(...) end
function GetHostName(...) end
function GetPredictionPlayer(...) end
function GetRenderTarget(...) end
function GetRenderTargetEx(...) end
function GetViewEntity(...) end
function HSLToColor(...) end
function HSVToColor(...) end
function HTTP(...) end
function IncludeCS(p1) end
function IsColor(p1) end
function IsEnemyEntityName(p1) end
function IsEntity(...) end
function IsFirstTimePredicted(...) end
function IsFriendEntityName(p1) end
function IsMounted(p1) end
function IsTableOfEntitiesValid(p1) end
function IsUselessModel(p1) end
function IsValid(p1) end
function JS_Language(p1) end
function JS_Utility(p1) end
function JS_Workshop(p1) end
function Label(p1,p2) end
function Lerp(p1,p2,p3) end
function LerpAngle(...) end
function LerpVector(...) end
function LoadPresets(...) end
function LocalPlayer(...) end
function LocalToWorld(...) end
function Localize(...) end
function Material(p1,p2) end
function Matrix(...) end
function Mesh(...) end
function Model(p1) end
function Msg(...) end
function MsgAll(...) end
function MsgC(...) end
function MsgN(...) end
function NamedColor(...) end
function NumModelSkins(p1) end
function OnModelLoaded(p1,p2,p3,p4,p5,p6,p7) end
function OrderVectors(...) end
function Particle(p1) end
function ParticleEffect(...) end
function ParticleEffectAttach(...) end
function ParticleEmitter(...) end
function Path(...) end
function Player(...) end
function PositionSpawnIcon(p1,p2,p3) end
function PrecacheParticleSystem(...) end
function PrecacheScene(...) end
function PrecacheSentenceFile(...) end
function PrecacheSentenceGroup(...) end
function PrintMessage(...) end
function PrintTable(p1,p2,p3) end
function ProjectedTexture(...) end
function ProtectedCall(...) end
function RandomPairs(p1,p2) end
function RealFrameTime() end
function RealTime(...) end
function RecipientFilter(...) end
function RegisterDermaMenuForClose(p1) end
function RememberCursorPosition() end
function RemoveTooltip() end
function RenderAngles(...) end
function RenderDoF(p1,p2,p3,p4,p5,p6,p7,p8,p9) end
function RenderStereoscopy(p1,p2) end
function RenderSuperDoF(p1,p2,p3) end
function RestoreCursorPosition() end
function RunConsoleCommand(...) end
function RunString(...) end
function RunStringEx(...) end
function SQLStr(p1,p2) end
function SScale(p1) end
function STNDRD(p1) end
function SafeRemoveEntity(p1) end
function SafeRemoveEntityDelayed(p1,p2) end
function SavePresets(...) end
function ScrH(...) end
function ScrW(...) end
function ScreenScale(p1) end
function SendUserMessage(...) end
function SentenceDuration(...) end
function ServerLog(...) end
function SetClipboardText(...) end
function SetGlobal2Angle(...) end
function SetGlobal2Bool(...) end
function SetGlobal2Entity(...) end
function SetGlobal2Float(...) end
function SetGlobal2Int(...) end
function SetGlobal2String(...) end
function SetGlobal2Var(...) end
function SetGlobal2Vector(...) end
function SetGlobalAngle(...) end
function SetGlobalBool(...) end
function SetGlobalEntity(...) end
function SetGlobalFloat(...) end
function SetGlobalInt(...) end
function SetGlobalString(...) end
function SetGlobalVar(...) end
function SetGlobalVector(...) end
function SetPhysConstraintSystem(...) end
function SortedPairs(p1,p2) end
function SortedPairsByMemberValue(p1,p2,p3) end
function SortedPairsByValue(p1,p2) end
function Sound(p1) end
function SoundDuration(...) end
function SuppressHostEvents(...) end
function SysTime(...) end
function TauntCamera() end
function TextEntryLoseFocus(p1,p2) end
function TimedCos(p1,p2,p3,p4) end
function TimedSin(p1,p2,p3,p4) end
function TypeID(...) end
function UTIL_IsUselessModel(p1) end
function UnPredictedCurTime(...) end
function VGUIFrameTime(...) end
function VGUIRect(p1,p2,p3,p4) end
function ValidPanel(p1) end
function Vector(...) end
function VectorRand(p1,p2) end
function VisualizeLayout(p1) end
function WorkshopFileBase(p1,p2) end
function WorldToLocal(...) end
function fnator(p1) end
function include(...) end
function isangle(...) end
function isbool(...) end
function isentity(...) end
function isfunction(...) end
function ismatrix(...) end
function isnumber(...) end
function ispanel(...) end
function isstring(...) end
function istable(...) end
function isvector(...) end
function magicPrint(...) end
function plys() end
function tobool(p1) end