--- @meta

--- Table structure used GM:CalcView and GM:CalcVehicleView hook.  
--- @class SCamData
--- @field origin GVector @The camera's position
--- @field angles GAngle @The camera's angles
--- @field fov number @The camera's FOV
--- @field znear number @Distance to near clipping plane
--- @field zfar number @Distance to far clipping plane
--- @field drawviewer? boolean @Set true to draw local players player model.
--- @field ortho? table @If set, enables orthographic mode
