--- @meta

--- Table returned by debug.getinfo.  
--- ℹ **NOTE**: If a filter is applied to debug.getinfo, some members may not exist!  
--- For functions defined in C/C++, the following members will always have the given values:  
--- * what = "C"  
--- * source = "[C]"  
--- * nparams = 0  
--- * isvararg = true  
--- * namewhat = ""  
--- * short_src = "[C]"  
--- * linedefined = -1  
--- * currentline = -1  
--- * lastlinedefined = -1  
--- @class SDebugInfo
--- @field func function @Reference to the function that was passed in
--- @field linedefined number @The line where the function definiton starts (where "function" is located)
--- @field lastlinedefined number @The line the function definition ended (where "end" is located)
--- @field source string @The path to the file where the passed function is defined prepended by an @ (ex
--- @field short_src string @The shortened name of the source (without the @)
--- @field what string @The language used
--- @field currentline number @The current line
--- @field name string @The function name
--- @field namewhat string @The function "type"
--- @field isvararg boolean @Whether the function is variadic (has a `...` argument)
--- @field nparams number @The number of arguments the function uses excluding varargs
--- @field nups number @Upvalue count
--- @field activelines table @A table of all the active lines in the function - that is, lines with code that actually does something (not blank lines or lines with comme
