--- @meta

--- Table structure used for util.TraceLine.  
--- @class STrace
--- @field start? GVector @The start position of the trace
--- @field endpos? GVector @The end position of the trace
--- @field filter? GEntity|GEntity[]|string[]|function @Things the trace should not hit
--- @field mask? EMASK @The trace mask Enums/MASK
--- @field collisiongroup? ECOLLISION_GROUP @The collision group Enums/COLLISION_GROUP
--- @field ignoreworld? boolean @Should the trace ignore world or not
--- @field output? STraceResult @If set, the trace result will be written to the supplied table instead of returning a new table
--- @field whitelist? boolean @Turns the `filter` field into a whitelist, if it is a table.
--- @field hitclientonly? boolean @Enables traces to hit clientside only entities
