--- @meta

--- The structure used by Structures/VehicleParams.  
--- @class SVehicleParamsSteering
--- @field boostSteeringRateFactor number
--- @field boostSteeringRestRateFactor number
--- @field brakeSteeringRateFactor number
--- @field degreesBoost number @The maximum angle at which the vehicle can turn while boosting
--- @field degreesFast number @The maximum angle at which the vehicle can turn while moving at max speed and not boosting
--- @field degreesSlow number @The maximum angle at which the vehicle can turn while moving slowest
--- @field dustCloud boolean @Disabled in Garry's Mod
--- @field isSkidAllowed boolean @Whether the vehicle is allowed to skid/drift
--- @field powerSlideAccel number @In Hammer Units
--- @field speedFast number
--- @field speedSlow number
--- @field steeringExponent number
--- @field steeringRateFast number
--- @field steeringRateSlow number
--- @field steeringRestRateFast number
--- @field steeringRestRateSlow number
--- @field throttleSteeringRestRateFactor number
--- @field turnThrottleReduceFast number
--- @field turnThrottleReduceSlow number
